[theme]
base = "dark"
primaryColor = "#00F2FE"
backgroundColor = "#070A0F"
secondaryBackgroundColor = "#0E1420"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = false
port = 8501
enableCORS = false
enableXsrfProtection = false
